apiVersion: v1
kind: Service
metadata:
  name: graphql-server
  namespace: graphql-server-gateway
spec:
  selector:
    app: graphql-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP